(()=> {
  const D={
    es:{
"ab.title":"Ablación de lambda · v0.7",
"ab.intro":"Siete políticas, las mismas jornadas. Aislamos el efecto de conservar cobertura futura, sin buscar semillas favorables.",
"ab.run":"Ejecutar barrido",
"ab.cancel":"Cancelar",
"ab.reference":"Referencia de las diferencias",
"ab.zero":"EcoDispatch λ = 0",
"ab.axis":"Eje horizontal",
"ab.served":"Cobertura (incidentes/jornada)",
"ab.meanEta":"ETA medio (min)",
"ab.p95Eta":"P95 diario medio (min)",
"ab.distance":"Distancia (km/jornada)",
"ab.severityDelay":"Retraso ponderado (gravedad·min/jornada)",
"ab.policy":"Política",
"ab.front":"Frente de Pareto",
"ab.dominated":"Dominada",
"ab.ready":"Preparado · solo perfil normal",
"ab.complete":"{n} jornadas por política · semilla: {seed}",
"ab.error":"No se pudo completar el barrido. Vuelve a intentarlo; consulta la consola si persiste.",
"ab.tableHelp":"Medias absolutas y Δ [IC95] frente a la referencia elegida. Selecciona una política para resaltarla. Cobertura: mayor es mejor; el resto requiere valorar el intercambio con cobertura.",
"ab.chartTitle":"Cobertura frente a ETA o distancia",
"ab.chartHelp":"Verde: no dominada en las tres dimensiones (cobertura ↑, ETA ↓, distancia ↓), incluyendo Greedy. Gris: dominada. Cambia el eje para explorar las proyecciones; selecciona un punto o una fila. La proyección 2D no define el frente 3D.",
"ab.method":"Protocolo y límites",
"ab.method1":"500 escenarios por defecto; opción 1000. λ ∈ {0, 0.1, 0.2, 0.35, 0.5, 1, 2}. Cada jornada normal contiene 120 incidentes. Semilla = base|normal|day|índice (desde 0), igual que v0.6. Los eventos se generan una sola vez por jornada y se reutilizan para todas las políticas; cada política reinicia la misma flota en las mismas bases k-median. No hay selección ni filtrado de jornadas.",
"ab.method2":"Score = gravedad × ETA + 0.0005 × emisiones (g) + 0.05 × distancia (km) + λ × Δ exposición. Greedy minimiza distancia factible: no equivale a λ=0. Lambda conserva la escala de v0.6, sin normalización adicional. Todas las políticas desconocen incidentes futuros.",
"ab.method3":"Cobertura = atendidos de 120; distancia = km totales por jornada. ETA es la media de atendidos; P95 es el valor ordenado en floor(0.95 × (atendidos−1)), conservando la convención v0.6. Se promedian los P95 diarios, no se agrupan todos los incidentes. Retraso ponderado = suma de gravedad × ETA de atendidos; no penaliza incidentes sin atender. Si ninguno se atiende, ETA y P95 son indefinidos: se excluyen esos pares y se informa n efectivo.",
"ab.method4":"Para cada métrica y referencia: dᵢ = resultadoᵢ(λ) − resultadoᵢ(referencia); IC95 aproximado = media(d) ± 1.96 × s(d)/√n, con desviación muestral. La unidad independiente es la jornada. Son intervalos puntuales sin ajuste por comparaciones múltiples, no intervalos de predicción. El frente usa medias muestrales, no significación estadística. No se elige un lambda ganador ni una utilidad implícita.",
"ab.method5":"Modelo sintético: distancias geodésicas, velocidades fijas, sin tiempos de servicio ni ocupación simultánea; el recurso queda en el incidente tras atenderlo. La flota y el mapa de riesgo son fijos: la incertidumbre solo corresponde al generador de jornadas. Los stress tests están separados y no entran en este estudio. No demuestra eficacia operativa ni reproduce garantías de los resultados teóricos de OpenAI.",
"ab.docs":"Metodología completa y reproducción ↗",
"ab.nav":"Lambda",
      "brand.subtitle":"Laboratorio abierto de investigación","nav.lab":"Experimentos","nav.results":"Resultados","nav.validation":"Validación","nav.research":"Investigación","nav.evolution":"Evolución",
      "hero.eyebrow":"INVESTIGACIÓN ABIERTA · v0.7","hero.title":"¿Cuánta capacidad desperdiciamos por <span>asignar mal</span> los recursos?","hero.lede":"EcoDispatch separa el problema en tres capas: dónde colocar recursos antes de una emergencia, cómo asignarlos cuando llegan varios incidentes a la vez y cómo mantener buena cobertura durante una jornada completa.","hero.cta":"Ejecutar banco de pruebas","hero.method":"Ver metodología",
      "pipe.placement":"Preposicionamiento","pipe.placementSub":"k-median ponderado por riesgo","pipe.crisis":"Crisis simultánea","pipe.crisisSub":"gravedad cubierta → cobertura → coste","pipe.day":"Jornada completa","pipe.daySub":"política online sensible a cobertura futura","pipe.measure":"Medir","pipe.measureSub":"cobertura, ETA, P95, distancia y daño",
      "summary.placement":"Preposicionamiento","summary.placementSub":"vs despliegue medio posible","summary.crisis":"Crisis simultánea","summary.crisisSub":"incidentes extra cubiertos","summary.day":"Jornada completa","summary.daySub":"diferencia de cobertura","summary.seed":"Semilla","summary.seedSub":"experimento reproducible",
      "lab.eyebrow":"BANCO DE PRUEBAS v0.6","lab.title":"Tres experimentos. Tres fuentes distintas de eficiencia.","lab.copy":"No buscamos una cifra única. Queremos aislar qué mejora viene de colocar mejor, cuál viene de asignar globalmente y cuál viene de conservar cobertura futura.",
      "controls.seed":"Semilla","controls.seedHelp":"Misma semilla = mismos escenarios.","controls.profile":"Perfil","controls.normal":"Normal","controls.stress":"Stress test","controls.profileHelp":"Stress busca conflictos difíciles de asignación y los etiqueta como tales.","controls.run":"▶ Ejecutar los 3 experimentos",
      "tabs.placement":"Preposicionamiento","tabs.placementSub":"¿Dónde esperar?","tabs.crisis":"Crisis simultánea","tabs.crisisSub":"¿Quién atiende a quién?","tabs.day":"Jornada completa","tabs.daySub":"¿Qué decisión deja mejor el sistema?",
      "placement.mapKicker":"MAPA DE RIESGO","placement.mapTitle":"Bases elegidas por k-median","placement.method":"exacto · 56 combinaciones","map.note":"coordenadas reales · esquema no cartográfico","placement.bigLabel":"Reducción de exposición ponderada","placement.bigCopy":"frente al promedio de todas las configuraciones posibles de 3 bases.","placement.opt":"EcoDispatch","placement.optSub":"objetivo ponderado","placement.avg":"Despliegue medio","placement.avgSub":"media de 56 configuraciones","placement.bases":"Bases óptimas","placement.whyTitle":"¿Dónde aparece la eficiencia?","placement.why":"No crea más brigadas: reduce la distancia esperada entre los recursos y las zonas donde el riesgo ponderado es mayor.",
      "crisis.stressTitle":"STRESS TEST DE ASIGNACIÓN","crisis.stressCopy":"El generador busca un escenario con conflicto real entre capacidades. No representa el promedio diario.","crisis.mapKicker":"INCIDENTES SIMULTÁNEOS","crisis.mapTitle":"Asignación global de una flota limitada","crisis.method":"matching exacto pequeño","crisis.covered":"incidentes cubiertos","crisis.bigLabel":"Recursos aprovechados mejor","crisis.greedyCost":"Coste Greedy","crisis.ecoCost":"Coste EcoDispatch",
      "day.stressTitle":"STRESS TEST ONLINE","day.stressCopy":"En modo stress se busca una jornada donde mantener cobertura futura importe. Está etiquetado para no confundirlo con rendimiento promedio.","day.visualKicker":"120 INCIDENTES SECUENCIALES","day.visualTitle":"Greedy vs política online sensible a riesgo","day.method":"sin conocer el futuro","day.coverage":"Cobertura","day.meanEta":"ETA medio","day.p95":"ETA P95","day.distance":"Distancia","day.bigLabel":"Diferencia de cobertura","day.whyTitle":"La diferencia clave","day.why":"Greedy minimiza el viaje actual. EcoDispatch añade una penalización por dejar mal cubierta la distribución futura del riesgo.",
      "research.eyebrow":"CONTEXTO MATEMÁTICO","research.title":"De resultados teóricos a experimentos medibles.","research.copy":"La web distingue deliberadamente entre el resultado matemático publicado y nuestra aplicación experimental.","research.kmedian":"Inspira la capa de preposicionamiento: elegir dónde deben esperar los recursos.","research.matching":"Inspira la asignación global. En v0.6 priorizamos gravedad total cubierta, después número de incidentes y finalmente coste secundario.","research.kserver":"Inspira el problema online: cada movimiento cambia la posición desde la que responderás al futuro.","research.disclaimer":"EcoDispatch es un prototipo independiente. Está inspirado por resultados matemáticos públicos de OpenAI, pero no está afiliado, financiado ni respaldado por OpenAI.","research.link":"Repositorio público de matemáticas de OpenAI ↗",
      "evolution.eyebrow":"BUILD IN PUBLIC","evolution.title":"Evolución del proyecto","evolution.copy":"Cada versión deja una huella reproducible de qué cambió y qué aprendimos.","limits.eyebrow":"LÍMITES","limits.title":"Banco de pruebas, no sistema operativo real.","limits.copy":"Los incidentes, bases y perfiles de riesgo son sintéticos sobre coordenadas reales de Málaga. Los stress tests buscan deliberadamente casos difíciles; la web los etiqueta para no presentarlos como rendimiento medio. Las rutas reales, tiempos de servicio e incidentes simultáneos con datos reales llegarán en versiones posteriores.","footer":"EcoDispatch · prototipo abierto de investigación",
      "mc.eyebrow":"VALIDACIÓN MONTE CARLO · v0.6","mc.title":"Una captura no demuestra nada. Cientos de escenarios empiezan a hacerlo.","mc.copy":"Estas simulaciones usan el perfil normal, sin buscar casos favorables. Resumimos la distribución completa de diferencias EcoDispatch − Greedy.","mc.samples":"Escenarios","mc.seed":"Semilla base","mc.run":"▶ Ejecutar validación","mc.ready":"Preparado","mc.progress":"Procesando {done}/{total}","mc.complete":"{n} escenarios completados","mc.crisisKicker":"CRISIS SIMULTÁNEA","mc.crisisTitle":"Matching con prioridad de gravedad","mc.severityDiff":"Δ gravedad cubierta media","mc.coverDiff":"Δ cobertura","mc.winRate":"Eco gana gravedad","mc.ofScenarios":"de escenarios","mc.severityUnits":"gravedad","mc.dayKicker":"JORNADA COMPLETA","mc.dayTitle":"120 incidentes · política online","mc.dayCover":"Δ cobertura media","mc.etaDiff":"Δ ETA medio","mc.p95Diff":"Δ ETA P95","mc.distanceDiff":"Δ distancia","mc.coverWin":"Eco gana cobertura","mc.coverLose":"Eco pierde cobertura","mc.methodTitle":"Cómo leer estos resultados","mc.methodCopy":"Cada escenario se genera de forma independiente a partir de una semilla reproducible. El intervalo mostrado es un IC del 95 % para la media (aproximación normal). P5/P50/P95 describen la distribución empírica. Los stress tests de arriba no entran en esta validación.","dynamic.crisisStorySeverity":"EcoDispatch cubre +{delta} puntos de gravedad total ({eco} vs {greedy}) antes de comparar cobertura y coste.","dynamic.extraIncidents":"{n} incidentes más","dynamic.sameCoverage":"misma cobertura","dynamic.crisisStoryMore":"El matching global cubre {eco} de {total}; greedy cubre {greedy}. La diferencia aparece porque reservar el recurso versátil para el incidente correcto evita bloquear otras asignaciones.","dynamic.crisisStoryCost":"Ambos cubren {served}, pero la asignación global reduce el coste secundario un {pct}%.","dynamic.dayMore":"EcoDispatch atiende {n} incidentes más durante la jornada.","dynamic.daySame":"Ambos atienden {n}; EcoDispatch reduce el ETA medio un {pct}%.","dynamic.eta":"ETA medio {eta} min","dynamic.assigned":"{resource} → {incident}","dynamic.unassigned":"sin asignar","dynamic.timelineShot":"Captura pendiente"
    },
    en:{
"ab.title":"Lambda ablation · v0.7",
"ab.intro":"Seven policies, identical operating days. Isolate the effect of preserving future coverage without searching for favorable seeds.",
"ab.run":"Run lambda sweep",
"ab.cancel":"Cancel",
"ab.reference":"Difference reference",
"ab.zero":"EcoDispatch λ = 0",
"ab.axis":"Horizontal axis",
"ab.served":"Coverage (incidents/day)",
"ab.meanEta":"Mean ETA (min)",
"ab.p95Eta":"Mean daily P95 (min)",
"ab.distance":"Distance (km/day)",
"ab.severityDelay":"Severity-weighted delay (severity·min/day)",
"ab.policy":"Policy",
"ab.front":"Pareto front",
"ab.dominated":"Dominated",
"ab.ready":"Ready · normal profile only",
"ab.complete":"{n} days per policy · seed: {seed}",
"ab.error":"The sweep could not complete. Try again; check the console if the problem persists.",
"ab.tableHelp":"Absolute means and Δ [95% CI] against the selected reference. Select a policy to highlight it. Higher coverage is better; other metrics must be considered alongside coverage.",
"ab.chartTitle":"Coverage versus ETA or distance",
"ab.chartHelp":"Green: non-dominated in all three dimensions (coverage ↑, ETA ↓, distance ↓), including Greedy. Gray: dominated. Switch axes to explore projections; select a point or row. The 2D projection does not define the 3D front.",
"ab.method":"Protocol and limitations",
"ab.method1":"500 scenarios by default; 1000 optional. λ ∈ {0, 0.1, 0.2, 0.35, 0.5, 1, 2}. Each normal day has 120 incidents. Seed = base|normal|day|index (starting at 0), as in v0.6. Events are generated once per day and reused by all policies; each policy resets the same fleet at the same k-median bases. No days are selected or filtered.",
"ab.method2":"Score = severity × ETA + 0.0005 × emissions (g) + 0.05 × distance (km) + λ × Δ exposure. Greedy minimizes feasible distance: it is not equivalent to λ=0. Lambda retains the v0.6 scale without additional normalization. All policies are unaware of future incidents.",
"ab.method3":"Coverage = served out of 120; distance = total km per day. ETA averages served incidents; P95 uses the sorted value at floor(0.95 × (served−1)), preserving the v0.6 convention. Daily P95s are averaged, rather than pooling incidents. Severity-weighted delay = sum of severity × ETA over served incidents; unserved incidents incur no penalty. If none are served, ETA and P95 are undefined: these pairs are omitted and effective n is reported.",
"ab.method4":"For each metric and reference: dᵢ = resultᵢ(λ) − resultᵢ(reference); approximate 95% CI = mean(d) ± 1.96 × s(d)/√n, using sample standard deviation. The independent unit is a day. Intervals are pointwise, unadjusted for multiple comparisons, and are not prediction intervals. The front uses sample means, not statistical significance. No winning lambda or implicit utility is chosen.",
"ab.method5":"Synthetic model: geodesic distances, fixed speeds, no service durations or simultaneous occupancy; resources remain at the served incident. Fleet and risk map are fixed: uncertainty only concerns the day generator. Stress tests are separate and excluded. This does not establish operational effectiveness or inherit guarantees from OpenAI theoretical results.",
"ab.docs":"Full methodology and reproduction ↗",
"ab.nav":"Lambda",
      "brand.subtitle":"Open research lab","nav.lab":"Experiments","nav.results":"Results","nav.validation":"Validation","nav.research":"Research","nav.evolution":"Evolution",
      "hero.eyebrow":"OPEN RESEARCH · v0.7","hero.title":"How much capacity do we waste by <span>allocating resources badly?</span>","hero.lede":"EcoDispatch separates the problem into three layers: where to position resources before an emergency, how to assign them when several incidents arrive at once, and how to preserve coverage throughout a full operating day.","hero.cta":"Run the research suite","hero.method":"View methodology",
      "pipe.placement":"Pre-positioning","pipe.placementSub":"risk-weighted k-median","pipe.crisis":"Simultaneous crisis","pipe.crisisSub":"severity covered → coverage → cost","pipe.day":"Full operating day","pipe.daySub":"online policy aware of future coverage","pipe.measure":"Measure","pipe.measureSub":"coverage, ETA, P95, distance and harm",
      "summary.placement":"Pre-positioning","summary.placementSub":"vs average possible deployment","summary.crisis":"Simultaneous crisis","summary.crisisSub":"extra incidents covered","summary.day":"Full day","summary.daySub":"coverage difference","summary.seed":"Seed","summary.seedSub":"reproducible experiment",
      "lab.eyebrow":"RESEARCH SUITE v0.6","lab.title":"Three experiments. Three different sources of efficiency.","lab.copy":"We are not looking for one magic number. We isolate how much comes from better positioning, global assignment and preserving future coverage.",
      "controls.seed":"Seed","controls.seedHelp":"Same seed = same scenarios.","controls.profile":"Profile","controls.normal":"Normal","controls.stress":"Stress test","controls.profileHelp":"Stress deliberately searches for hard allocation conflicts and labels them as such.","controls.run":"▶ Run all 3 experiments",
      "tabs.placement":"Pre-positioning","tabs.placementSub":"Where should resources wait?","tabs.crisis":"Simultaneous crisis","tabs.crisisSub":"Who should respond to what?","tabs.day":"Full operating day","tabs.daySub":"Which decision leaves the system healthier?",
      "placement.mapKicker":"RISK MAP","placement.mapTitle":"Bases selected by k-median","placement.method":"exact · 56 combinations","map.note":"real coordinates · non-cartographic schematic","placement.bigLabel":"Weighted exposure reduction","placement.bigCopy":"against the average of every possible 3-base configuration.","placement.opt":"EcoDispatch","placement.optSub":"weighted objective","placement.avg":"Average deployment","placement.avgSub":"mean of 56 configurations","placement.bases":"Optimal bases","placement.whyTitle":"Where does the efficiency come from?","placement.why":"It does not create more crews. It reduces the expected distance between resources and the places where weighted risk is highest.",
      "crisis.stressTitle":"ALLOCATION STRESS TEST","crisis.stressCopy":"The generator deliberately searches for a real capability conflict. This is not presented as average daily performance.","crisis.mapKicker":"SIMULTANEOUS INCIDENTS","crisis.mapTitle":"Global assignment of a limited fleet","crisis.method":"small exact matching","crisis.covered":"incidents covered","crisis.bigLabel":"Better use of the same resources","crisis.greedyCost":"Greedy cost","crisis.ecoCost":"EcoDispatch cost",
      "day.stressTitle":"ONLINE STRESS TEST","day.stressCopy":"In stress mode we search for a day where preserving future coverage matters. It is explicitly labeled so it is not confused with average-case performance.","day.visualKicker":"120 SEQUENTIAL INCIDENTS","day.visualTitle":"Greedy vs risk-aware online policy","day.method":"no future knowledge","day.coverage":"Coverage","day.meanEta":"Mean ETA","day.p95":"P95 ETA","day.distance":"Distance","day.bigLabel":"Coverage difference","day.whyTitle":"The key difference","day.why":"Greedy minimizes the current trip. EcoDispatch also penalizes decisions that leave the future risk distribution poorly covered.",
      "research.eyebrow":"MATHEMATICAL CONTEXT","research.title":"From theoretical results to measurable experiments.","research.copy":"The site deliberately separates the published mathematical result from our experimental application.","research.kmedian":"Inspires the pre-positioning layer: deciding where resources should wait.","research.matching":"Inspires global assignment. In v0.6 we prioritize total severity covered, then incident count, and finally secondary cost.","research.kserver":"Inspires the online problem: every move changes where you will respond from next.","research.disclaimer":"EcoDispatch is an independent prototype. It is inspired by public OpenAI mathematics results, but is not affiliated with, funded by, or endorsed by OpenAI.","research.link":"OpenAI public mathematics repository ↗",
      "evolution.eyebrow":"BUILD IN PUBLIC","evolution.title":"Project evolution","evolution.copy":"Each version leaves a reproducible record of what changed and what we learned.","limits.eyebrow":"LIMITS","limits.title":"A research benchmark, not an operational emergency system.","limits.copy":"Incidents, bases and risk profiles are synthetic over real Málaga coordinates. Stress tests deliberately search for hard cases and are labeled so they are not presented as average performance. Real road routing, service times and real-world simultaneous incident data will come in later versions.","footer":"EcoDispatch · open research prototype",
      "mc.eyebrow":"MONTE CARLO VALIDATION · v0.6","mc.title":"One screenshot proves nothing. Hundreds of scenarios start to.","mc.copy":"These simulations use the normal profile without searching for favorable cases. We summarize the full distribution of EcoDispatch − Greedy differences.","mc.samples":"Scenarios","mc.seed":"Base seed","mc.run":"▶ Run validation","mc.ready":"Ready","mc.progress":"Processing {done}/{total}","mc.complete":"{n} scenarios completed","mc.crisisKicker":"SIMULTANEOUS CRISIS","mc.crisisTitle":"Severity-prioritized matching","mc.severityDiff":"Mean Δ severity covered","mc.coverDiff":"Δ coverage","mc.winRate":"Eco wins severity","mc.ofScenarios":"of scenarios","mc.severityUnits":"severity","mc.dayKicker":"FULL OPERATING DAY","mc.dayTitle":"120 incidents · online policy","mc.dayCover":"Mean Δ coverage","mc.etaDiff":"Δ mean ETA","mc.p95Diff":"Δ P95 ETA","mc.distanceDiff":"Δ distance","mc.coverWin":"Eco wins coverage","mc.coverLose":"Eco loses coverage","mc.methodTitle":"How to read these results","mc.methodCopy":"Each scenario is generated independently from a reproducible seed. The interval shown is a 95% confidence interval for the mean (normal approximation). P5/P50/P95 describe the empirical distribution. Stress tests above are excluded from this validation.","dynamic.crisisStorySeverity":"EcoDispatch covers +{delta} total severity points ({eco} vs {greedy}) before comparing incident count and cost.","dynamic.extraIncidents":"{n} more incidents","dynamic.sameCoverage":"same coverage","dynamic.crisisStoryMore":"Global matching covers {eco} of {total}; greedy covers {greedy}. The difference appears because reserving a versatile resource for the right incident avoids blocking other assignments.","dynamic.crisisStoryCost":"Both cover {served}, but global assignment cuts secondary cost by {pct}%.","dynamic.dayMore":"EcoDispatch serves {n} more incidents during the day.","dynamic.daySame":"Both serve {n}; EcoDispatch reduces mean ETA by {pct}%.","dynamic.eta":"mean ETA {eta} min","dynamic.assigned":"{resource} → {incident}","dynamic.unassigned":"unassigned","dynamic.timelineShot":"Screenshot pending"
    }
  };
  const requested=new URLSearchParams(location.search).get("lang")||localStorage.getItem("ecodispatch-lang");
  let lang=requested&&D[requested]?requested:((navigator.language||"").toLowerCase().startsWith("es")?"es":"en");
  function t(key,vars={}){let s=(D[lang]&&D[lang][key])||D.en[key]||key;for(const [k,v] of Object.entries(vars))s=s.replaceAll("{"+k+"}",String(v));return s;}
  function apply(){
    document.documentElement.lang=lang;
    document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));
    document.querySelectorAll("[data-i18n-html]").forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));
    document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));
  }
  function setLang(next){
    if(!D[next])return;
    lang=next;localStorage.setItem("ecodispatch-lang",lang);
    const u=new URL(location.href);u.searchParams.set("lang",lang);history.replaceState(null,"",u);
    apply();window.dispatchEvent(new CustomEvent("languagechange",{detail:{lang}}));
  }
  document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));apply();});
  window.I18N={t,apply,setLang,get lang(){return lang;}};
})();